development:
  adapter: mysql2
  encoding: utf8
  database: file_uploader_db
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: file_uploader_test
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock